### ISSUE TITLE
the demo always has error,about module 'autosar' has no attribute 'workspace'

### ISSUE THREAD

**Issue by Eng2Mot** [cogu/autosar#27]
the demo always has error,about module 'autosar' has no attribute 'workspace'

Traceback (most recent call last):
  File "C:\Users\gz03232\Documents\autosar.py", line 1, in <module>
    import autosar
  File "C:\Users\gz03232\Documents\autosar.py", line 3, in <module>
    ws = autosar.workspace(version='4.2.2')
AttributeError: module 'autosar' has no attribute 'workspace'
>>> 

demo application as follow:
import autosar
    
ws = autosar.workspace(version='4.2.2')
        
ws.createPackage('DataTypes', role='DataType')
ws.createPackage('Constants', role="Constant")
ws.createPackage('PortInterfaces', role="PortInterface")
ws.createPackage('ModeDclrGroups', role="ModeDclrGroup")
ws.createPackage('ComponentTypes', role='ComponentType')
  
#save the file as XML
ws.saveXML('Workspace.arxml')

    
ws = autosar.workspace(version='4.2.2')
        
ws.createPackage('DataTypes', role='DataType')
ws.createPackage('Constants', role="Constant")
ws.createPackage('PortInterfaces', role="PortInterface")
ws.createPackage('ModeDclrGroups', role="ModeDclrGroup")
ws.createPackage('ComponentTypes', role='ComponentType')

#save workspace packages into XML files
ws.saveXML('DataTypes.arxml', filters=['/DataTypes'])
ws.saveXML('Constants.arxml', filters=['/Constants'])
ws.saveXML('PortInterfaces.arxml', filters=['/PortInterfaces', '/ModeDclrGroups'])
ws.saveXML('ComponentTypes.arxml', filters=['/ComponentTypes'])

**Comment by cogu** [comment]
It seems you have named your own script file autosar.py and the Python engine seems to use that one as the actual python module "autosar".

Try renaming your script file to anything except "autosar.py", like "demo.py"

**Comment by cogu** [comment]
This issue is no longer relevant

**Comment by Sudhanva10** [comment]
@cogu Thanks man.
It looks like the solution which you gave is still relevant.
