### ISSUE TITLE
Error on Version and Schema for autosar 4

### ISSUE THREAD

**Issue by DeathThenNothing** [cogu/autosar#28]
(major, minor, patch, schema) = parseAutosarVersionAndSchema(xmlroot)
ValueError: not enough values to unpack (expected 4, got 3)

AUTOSAR xmlns="http://autosar.org/schema/r4.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://autosar.org/schema/r4.0 AUTOSAR_00044.xsd"

**Comment by DeathThenNothing** [comment]
It is ok with autosar_4-3-0 instead of AUTOSAR_00044

**Comment by cogu** [comment]
Versioning is defined in an AUTOSAR specification named "ARXML Serialization Rules". You are right in that it seems like they changed the definition in AUTOSAR 4.3 to allow such numbers as AUTOSAR_00044.xsd.

As I currently only support up to AUTOSAR 4.2 my Python module will not handle it.

I will keep this issue open for a while until I have time to implement the new versioning scheme.

Thanks for notifying me about the error.

**Comment by sperly** [comment]
I also noticed this today. We also use 4.3.1 with the AUTOSAR_00044.xsd

**Comment by cogu** [comment]
* All releases prior to v0.5.0 supports old format only (major, minor patch)
* Starting from v0.5.0 only the new format is supported (schema-version as an integer)
