### ISSUE TITLE
ComSpec for data elements in a port with multiple data elements

### ISSUE THREAD

**Issue by DeathThenNothing** [cogu/autosar#30]
ComSpec for individual data elements in a port cannot be created

**Comment by cogu** [comment]
You're probably right. The company that I work at that is using this technology has a policy to use only a single data element per port. Therefore I have not fully implemented support for multiple data elements as it hasn't been requested.

**Comment by cogu** [comment]
Multiple data elements is now possible in release v0.3.6. Please check the unit test suite for examples.
