### ISSUE TITLE
Is there any function to create arxmls with comm data ?

### ISSUE THREAD

**Issue by Purnanandj1994** [cogu/autosar#35]
with below data in arxmls

FIBEX-ELEMENTS
FIBEX-ELEMENT-REF-CONDITIONAL

**Comment by cogu** [comment]
Sorry, no there is no such API and its currently not planned.

**Comment by Purnanandj1994** [comment]
Can we have it as part of autosar 0.3.6 release

**Comment by cogu** [comment]
No, this project is focused on application SWC development which means those types of elements are out of scope. 
Once I have finished the necessary refactoring steps and merged to master, you are welcome to fork this open source project on Github and implement the feature you need.
