### ISSUE TITLE
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working

### ISSUE THREAD

**Issue by kallemooo** [cogu/autosar#42]
Using collections.Iterable or collections.Mapping direct is deprecated since Python 3.3. In future versions will it stop working.

Change to use collections.abc.Iterable or collections.abc.Mapping will solve this issue.

**Comment by cogu** [comment]
Hi, I've been away during Christmas. This was fixed a while back on my feature branch (among other things) and will be merged and released as part of v0.3.7.
