### ISSUE TITLE
Parser support for AR 4.x Complex Driver Component Type 

### ISSUE THREAD

**Issue by SHolzmann** [cogu/autosar#49]
First thanks for this great package. For AR 4.x the element name of an complex driver component type shall be "COMPLEX-DEVICE-DRIVER-SW-COMPONENT-TYPE'" instead of "COMPLEX-DEVICE-DRIVER-COMPONENT-TYPE". See /autosar/parser/component_parser.py

**Comment by cogu** [comment]
Thanks for finding it. I fixed it on master.

**Comment by SHolzmann** [comment]
Thanks for the fix
