### ISSUE TITLE
<PR-PORT-PROTOTYPE>

### ISSUE THREAD

**Issue by Tofeni** [cogu/autosar#54]
Hello,

i have 3 questions:

1) Is there a way to add <DESC> to an element?
2) It is possible to create Provider receiver port?
3) Why i can not crate ProvidePort if i have many elements in a PortInterface?

![Capture](https://user-images.githubusercontent.com/27285649/72592917-595ed780-390c-11ea-8801-b3b228dd3884.PNG)

Thank you,
Tofeni

**Comment by cogu** [comment]
Question 1: I'm not sure what you mean. Is it related to question 3?
Question 2: No, PR-PORT-PROTOTYPE has not been implemented in this Python package.
Question 3: You can certainly have many data elements in an interface. See test case test_create_nvblock_software_component in file ar4_component_test.py for example. 
@kallemooo Thanks for providing that test case.

**Comment by Tofeni** [comment]
1) at the first question i write <  desc> (DESC)

3) and at the 3th, i am trying this:
swc.createProvidePort('P_DiagNv_ParameterHandler_Cfg_PRDiagNv_ParameterHandler', '/PortInterfaces/IfDiagNv_ParameterHandler_Cfg', romBlockInitValue='0'), and i get next error:
![Capture](https://user-images.githubusercontent.com/27285649/72610873-3a267100-3931-11ea-815c-18d5376af71f.PNG)

i will try with the test case test_create_nvblock_software_component in file ar4_component_test.py

Thank you

**Comment by cogu** [comment]
Description fields are not implemented for ports.

Some time ago I refactored the XML parser to share common parsing code for tags that occurs often.

I will need to refactor the XML writer in a similar fashion so that it automatically handles common fields such as desc and admin-data without having to add them manually for every single XML element.

**Comment by cogu** [comment]
* Starting from v0.5.3 PR-PORTS are now supported
* Description elements are also supported for all elements, including ports.
