### ISSUE TITLE
AttributeError: module 'autosar.portinterface' has no attribute 'ModeGroup'

### ISSUE THREAD

**Issue by daiyinger** [cogu/autosar#69]
partition_test_disabled.py cause AttributeError: module 'autosar.portinterface' has no attribute 'ModeGroup', partition_test_disabled.py  is too old?

**Comment by cogu** [comment]
Yes, everything in the autosar.rte namespace is old and needs a complete upgrade/rewrite.

**Comment by cogu** [comment]
* Won't be fixed in v0.4.x.
* New implementation is planned for v0.8.0.
