### ISSUE TITLE
END-TO-END set in NONQUEUED-SENDER-COM-SPEC shal

### ISSUE THREAD

**Issue by gcbb** [cogu/autosar#86]
in file b \Lib\site-packages\autosar-0.3.11-py3.9.egg\autosar\writer\component_writer.py:365
应该改为
     lines.append(self.indent('<USES-END-TO-END-PROTECTION>{}</USES-END-TO-END-PROTECTION>'.format(self.toBooleanStr(comspec.useEndToEndProtection)), 1))
否则 arxml文件E2E的属性无法正常解析

**Comment by cogu** [comment]
* Supported in [v0.5.3](https://github.com/cogu/autosar/releases/tag/v0.5.3)
* Won't be fixed in v0.4.x.
