### ISSUE TITLE
multiply arxmls in one workspace

### ISSUE THREAD

**Issue by Han40** [cogu/autosar#88]
i want to load create RPort in A workspace's componentType, using Port interface in another arxml.
how to create one workspace with multiply arxmls.
how to load multiply arxmls into one workspace.

 thanks

**Comment by gcbb** [comment]
先用wks1加载arxml1
再用wks2加载arxml2
在wks2中直接引用wks1的portinterface就行

**Comment by Han40** [comment]
> 先用wks1加载arxml1 再用wks2加载arxml2 在wks2中直接引用wks1的portinterface就行

目前看下来没法 做到 跨 workspace 的方法来 引用 portInterface

**Comment by gcbb** [comment]
我百分百肯定可以的
查找出wks1的port interface路径，然后在wks2中引用
我就是这么干的

**Comment by Han40** [comment]
如何引用呢，直接路径名路径名就可以吗？ 还是要备注上 wks1:PortInterfaceRef ?
我看了代码里似乎一直在找 自己workspace 内的 PortInterfaceRef
可以看下源码里compoent.py 里的 createRequirePort 方法
我不知道你这边如何实现的呢？？？

**Comment by gcbb** [comment]
报歉，我查了下我自己的，，，我是在一个wks中，，，


我只是加我了两个arxml







---Original---
From: ***@***.***&gt;
Date: Mon, Apr 4, 2022 11:26 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [cogu/autosar] multiply arxmls in one workspace (Issue #88)




 
如何引用呢，直接路径名路径名就可以吗？ 还是要备注上 wks1:PortInterfaceRef ?
 我看了代码里似乎一直在找 自己workspace 内的 PortInterfaceRef
 可以看下源码里compoent.py 里的 createRequirePort 方法
 我不知道你这边如何实现的呢？？？

**Comment by cogu** [comment]
Already supported. Not sure what the issue really was.
